title: "SeongHyeon Noh"
url: "https://nohse.github.io"
name: "SeongHyeon Noh"
position: "undergraduate research student at Korea University"
location: "Seoul, Korea"
affiliation: "MIIL, Korea University"
email: "watercar67@naver.com"
google_scholar: "https://scholar.google.com/citations?user=yMJ8mCAAAAAJ&hl=en&oi=sra" 
github: "https://github.com/nohse"
linkedin: "https://www.linkedin.com/in/your-id/"
